<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="11" ignored="0" total="45" passed="34">
  <reporter-output>
  </reporter-output>
  <suite name="restassuredtestsuite" duration-ms="3659" started-at="2019-10-24T23:36:23Z" finished-at="2019-10-24T23:36:26Z">
    <groups>
    </groups>
    <test name="restassuredtests" duration-ms="3659" started-at="2019-10-24T23:36:23Z" finished-at="2019-10-24T23:36:26Z">
      <class name="putRequest.putRequest">
        <test-method status="PASS" signature="getEndPoint()[pri:0, instance:putRequest.putRequest@4909b8da]" name="getEndPoint" is-config="true" duration-ms="22" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPoint -->
        <test-method status="PASS" signature="testPutResponseCode()[pri:0, instance:putRequest.putRequest@4909b8da]" name="testPutResponseCode" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPutResponseCode -->
        <test-method status="PASS" signature="validateHeaders()[pri:0, instance:putRequest.putRequest@4909b8da]" name="validateHeaders" duration-ms="1" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHeaders -->
        <test-method status="PASS" signature="testPutResponseStatusLine()[pri:0, instance:putRequest.putRequest@4909b8da]" name="testPutResponseStatusLine" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPutResponseStatusLine -->
        <test-method status="PASS" signature="validateDB()[pri:0, instance:putRequest.putRequest@4909b8da]" name="validateDB" duration-ms="32" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDB -->
      </class> <!-- putRequest.putRequest -->
      <class name="putRequest.putProductCode">
        <test-method status="PASS" signature="getEndPoint()[pri:0, instance:putRequest.putProductCode@15975490]" name="getEndPoint" is-config="true" duration-ms="18" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPoint -->
        <test-method status="FAIL" signature="testPutResponseCode()[pri:0, instance:putRequest.putProductCode@15975490]" name="testPutResponseCode" duration-ms="1" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<404> but was:<200>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<404> but was:<200>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
at putRequest.putProductCode.testPutResponseCode(putProductCode.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPutResponseCode -->
      </class> <!-- putRequest.putProductCode -->
      <class name="putRequest.putMissingName">
        <test-method status="PASS" signature="getEndPoint()[pri:0, instance:putRequest.putMissingName@1936f0f5]" name="getEndPoint" is-config="true" duration-ms="20" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPoint -->
        <test-method status="PASS" signature="testPutResponseCode()[pri:0, instance:putRequest.putMissingName@1936f0f5]" name="testPutResponseCode" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPutResponseCode -->
        <test-method status="PASS" signature="validateHeaders()[pri:0, instance:putRequest.putMissingName@1936f0f5]" name="validateHeaders" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHeaders -->
        <test-method status="PASS" signature="testPutResponseStatusLine()[pri:0, instance:putRequest.putMissingName@1936f0f5]" name="testPutResponseStatusLine" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPutResponseStatusLine -->
        <test-method status="PASS" signature="validateDB()[pri:0, instance:putRequest.putMissingName@1936f0f5]" name="validateDB" duration-ms="37" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDB -->
      </class> <!-- putRequest.putMissingName -->
      <class name="postRequest.PostRequest">
        <test-method status="PASS" signature="getEndPoint()[pri:0, instance:postRequest.PostRequest@3567135c]" name="getEndPoint" is-config="true" duration-ms="67" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPoint -->
        <test-method status="PASS" signature="testPostResponseCode()[pri:0, instance:postRequest.PostRequest@3567135c]" name="testPostResponseCode" duration-ms="3" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostResponseCode -->
        <test-method status="PASS" signature="testPostResponseStatusLine()[pri:0, instance:postRequest.PostRequest@3567135c]" name="testPostResponseStatusLine" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostResponseStatusLine -->
        <test-method status="PASS" signature="validateDB()[pri:0, instance:postRequest.PostRequest@3567135c]" name="validateDB" duration-ms="47" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDB -->
      </class> <!-- postRequest.PostRequest -->
      <class name="putRequest.putMissingPrice">
        <test-method status="PASS" signature="getEndPoint()[pri:0, instance:putRequest.putMissingPrice@6615435c]" name="getEndPoint" is-config="true" duration-ms="24" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPoint -->
        <test-method status="PASS" signature="testPutResponseCode()[pri:0, instance:putRequest.putMissingPrice@6615435c]" name="testPutResponseCode" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPutResponseCode -->
        <test-method status="PASS" signature="testPutResponseStatusLine()[pri:0, instance:putRequest.putMissingPrice@6615435c]" name="testPutResponseStatusLine" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPutResponseStatusLine -->
        <test-method status="PASS" signature="validateDB()[pri:0, instance:putRequest.putMissingPrice@6615435c]" name="validateDB" duration-ms="47" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDB -->
        <test-method status="PASS" signature="validateHeaders()[pri:0, instance:putRequest.putMissingPrice@6615435c]" name="validateHeaders" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHeaders -->
      </class> <!-- putRequest.putMissingPrice -->
      <class name="getRequest.GetDataId">
        <test-method status="PASS" signature="getEndPointId()[pri:0, instance:getRequest.GetDataId@68837a77]" name="getEndPointId" is-config="true" duration-ms="29" started-at="2019-10-24T23:36:25Z" finished-at="2019-10-24T23:36:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPointId -->
        <test-method status="PASS" signature="testResponseCode()[pri:0, instance:getRequest.GetDataId@68837a77]" name="testResponseCode" duration-ms="0" started-at="2019-10-24T23:36:25Z" finished-at="2019-10-24T23:36:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseCode -->
        <test-method status="PASS" signature="testResponseLine()[pri:0, instance:getRequest.GetDataId@68837a77]" name="testResponseLine" duration-ms="0" started-at="2019-10-24T23:36:25Z" finished-at="2019-10-24T23:36:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseLine -->
        <test-method status="PASS" signature="testResponseDataId()[pri:0, instance:getRequest.GetDataId@68837a77]" name="testResponseDataId" duration-ms="518" started-at="2019-10-24T23:36:25Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseDataId -->
        <test-method status="FAIL" signature="validateResponseBody()[pri:0, instance:getRequest.GetDataId@68837a77]" name="validateResponseBody" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [product-code] but found [id]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [product-code] but found [id]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at getRequest.GetDataId.validateResponseBody(GetDataId.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateResponseBody -->
        <test-method status="PASS" signature="validateHeaders()[pri:0, instance:getRequest.GetDataId@68837a77]" name="validateHeaders" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHeaders -->
        <test-method status="FAIL" signature="validateDataType()[pri:0, instance:getRequest.GetDataId@68837a77]" name="validateDataType" duration-ms="13" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [float] but found [String]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [float] but found [String]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at getRequest.GetDataId.validateDataType(GetDataId.java:143)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDataType -->
      </class> <!-- getRequest.GetDataId -->
      <class name="getRequest.GetDataNegative">
        <test-method status="PASS" signature="getEndPointId()[pri:0, instance:getRequest.GetDataNegative@6be46e8f]" name="getEndPointId" is-config="true" duration-ms="26" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPointId -->
        <test-method status="PASS" signature="testResponseCode()[pri:0, instance:getRequest.GetDataNegative@6be46e8f]" name="testResponseCode" duration-ms="1" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseCode -->
        <test-method status="PASS" signature="testResponseLine()[pri:0, instance:getRequest.GetDataNegative@6be46e8f]" name="testResponseLine" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseLine -->
        <test-method status="PASS" signature="validateResponseBody()[pri:0, instance:getRequest.GetDataNegative@6be46e8f]" name="validateResponseBody" duration-ms="23" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateResponseBody -->
        <test-method status="FAIL" signature="validateHeaders()[pri:0, instance:getRequest.GetDataNegative@6be46e8f]" name="validateHeaders" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [application/json] but found [application/problem+json]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [application/json] but found [application/problem+json]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at getRequest.GetDataNegative.validateHeaders(GetDataNegative.java:102)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHeaders -->
      </class> <!-- getRequest.GetDataNegative -->
      <class name="putRequest.putProductPrice">
        <test-method status="PASS" signature="getEndPoint()[pri:0, instance:putRequest.putProductPrice@6b143ee9]" name="getEndPoint" is-config="true" duration-ms="21" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPoint -->
        <test-method status="FAIL" signature="testPutResponseCode()[pri:0, instance:putRequest.putProductPrice@6b143ee9]" name="testPutResponseCode" duration-ms="1" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<404> but was:<200>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<404> but was:<200>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
at putRequest.putProductPrice.testPutResponseCode(putProductPrice.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPutResponseCode -->
      </class> <!-- putRequest.putProductPrice -->
      <class name="postRequest.PostRequestId">
        <test-method status="PASS" signature="getEndPoint()[pri:0, instance:postRequest.PostRequestId@90f6bfd]" name="getEndPoint" is-config="true" duration-ms="18" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPoint -->
        <test-method status="FAIL" signature="testPostResponseCode()[pri:0, instance:postRequest.PostRequestId@90f6bfd]" name="testPostResponseCode" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<404> but was:<200>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<404> but was:<200>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:64)
at junit.framework.Assert.assertEquals(Assert.java:201)
at junit.framework.Assert.assertEquals(Assert.java:207)
at postRequest.PostRequestId.testPostResponseCode(PostRequestId.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostResponseCode -->
      </class> <!-- postRequest.PostRequestId -->
      <class name="getRequest.GetData">
        <test-method status="PASS" signature="getEndPoint()[pri:0, instance:getRequest.GetData@2d554825]" name="getEndPoint" is-config="true" duration-ms="2161" started-at="2019-10-24T23:36:23Z" finished-at="2019-10-24T23:36:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPoint -->
        <test-method status="PASS" signature="testResponseCode()[pri:0, instance:getRequest.GetData@2d554825]" name="testResponseCode" duration-ms="3" started-at="2019-10-24T23:36:25Z" finished-at="2019-10-24T23:36:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseCode -->
        <test-method status="PASS" signature="testResponseLine()[pri:0, instance:getRequest.GetData@2d554825]" name="testResponseLine" duration-ms="2" started-at="2019-10-24T23:36:25Z" finished-at="2019-10-24T23:36:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseLine -->
        <test-method status="FAIL" signature="validateResponseBody()[pri:0, instance:getRequest.GetData@2d554825]" name="validateResponseBody" duration-ms="187" started-at="2019-10-24T23:36:25Z" finished-at="2019-10-24T23:36:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [product-code] but found [id]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [product-code] but found [id]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at getRequest.GetData.validateResponseBody(GetData.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateResponseBody -->
        <test-method status="PASS" signature="validateHeaders()[pri:0, instance:getRequest.GetData@2d554825]" name="validateHeaders" duration-ms="21" started-at="2019-10-24T23:36:25Z" finished-at="2019-10-24T23:36:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHeaders -->
      </class> <!-- getRequest.GetData -->
      <class name="postRequest.PostRequestCode">
        <test-method status="PASS" signature="getEndPoint()[pri:0, instance:postRequest.PostRequestCode@4157f54e]" name="getEndPoint" is-config="true" duration-ms="25" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPoint -->
        <test-method status="PASS" signature="testPostResponseCode()[pri:0, instance:postRequest.PostRequestCode@4157f54e]" name="testPostResponseCode" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostResponseCode -->
        <test-method status="PASS" signature="validateDB()[pri:0, instance:postRequest.PostRequestCode@4157f54e]" name="validateDB" duration-ms="24" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDB -->
      </class> <!-- postRequest.PostRequestCode -->
      <class name="delete.deleteMissing">
        <test-method status="PASS" signature="getEndPoint()[pri:0, instance:delete.deleteMissing@2d3fcdbd]" name="getEndPoint" is-config="true" duration-ms="19" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPoint -->
        <test-method status="PASS" signature="testDeleteResponseCode()[pri:0, instance:delete.deleteMissing@2d3fcdbd]" name="testDeleteResponseCode" duration-ms="1" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteResponseCode -->
        <test-method status="PASS" signature="testDeleteResponseStatusLine()[pri:0, instance:delete.deleteMissing@2d3fcdbd]" name="testDeleteResponseStatusLine" duration-ms="2" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteResponseStatusLine -->
        <test-method status="FAIL" signature="validateHeaders()[pri:0, instance:delete.deleteMissing@2d3fcdbd]" name="validateHeaders" duration-ms="2" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<application/problem+json> but was:<application/json>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<application/problem+json> but was:<application/json>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
at delete.deleteMissing.validateHeaders(deleteMissing.java:92)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHeaders -->
        <test-method status="PASS" signature="testDeleteResponseBody()[pri:0, instance:delete.deleteMissing@2d3fcdbd]" name="testDeleteResponseBody" duration-ms="28" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteResponseBody -->
      </class> <!-- delete.deleteMissing -->
      <class name="delete.delete">
        <test-method status="PASS" signature="getEndPoint()[pri:0, instance:delete.delete@3a03464]" name="getEndPoint" is-config="true" duration-ms="47" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPoint -->
        <test-method status="PASS" signature="testDeleteResponseCode()[pri:0, instance:delete.delete@3a03464]" name="testDeleteResponseCode" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteResponseCode -->
        <test-method status="PASS" signature="testDeleteResponseStatusLine()[pri:0, instance:delete.delete@3a03464]" name="testDeleteResponseStatusLine" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteResponseStatusLine -->
        <test-method status="PASS" signature="validateHeaders()[pri:0, instance:delete.delete@3a03464]" name="validateHeaders" duration-ms="0" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHeaders -->
        <test-method status="PASS" signature="validateDB()[pri:0, instance:delete.delete@3a03464]" name="validateDB" duration-ms="14" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDB -->
      </class> <!-- delete.delete -->
      <class name="postRequest.postMissingNode">
        <test-method status="PASS" signature="getEndPoint()[pri:0, instance:postRequest.postMissingNode@327471b5]" name="getEndPoint" is-config="true" duration-ms="30" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPoint -->
        <test-method status="FAIL" signature="testPostResponseCode()[pri:0, instance:postRequest.postMissingNode@327471b5]" name="testPostResponseCode" duration-ms="1" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<404> but was:<400>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<404> but was:<400>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:64)
at junit.framework.Assert.assertEquals(Assert.java:201)
at junit.framework.Assert.assertEquals(Assert.java:207)
at postRequest.postMissingNode.testPostResponseCode(postMissingNode.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostResponseCode -->
        <test-method status="FAIL" signature="testPostResponseStatusLine()[pri:0, instance:postRequest.postMissingNode@327471b5]" name="testPostResponseStatusLine" duration-ms="1" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<...4...> but was:<...0...>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<...4...> but was:<...0...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at postRequest.postMissingNode.testPostResponseStatusLine(postMissingNode.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostResponseStatusLine -->
      </class> <!-- postRequest.postMissingNode -->
      <class name="putRequest.putId">
        <test-method status="PASS" signature="getEndPoint()[pri:0, instance:putRequest.putId@47f6473]" name="getEndPoint" is-config="true" duration-ms="21" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPoint -->
        <test-method status="FAIL" signature="testPutResponseCode()[pri:0, instance:putRequest.putId@47f6473]" name="testPutResponseCode" duration-ms="2" started-at="2019-10-24T23:36:26Z" finished-at="2019-10-24T23:36:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<404> but was:<200>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<404> but was:<200>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
at putRequest.putId.testPutResponseCode(putId.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPutResponseCode -->
      </class> <!-- putRequest.putId -->
    </test> <!-- restassuredtests -->
  </suite> <!-- restassuredtestsuite -->
</testng-results>
