<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2628" started-at="2019-10-24T21:00:51Z" finished-at="2019-10-24T21:00:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2628" started-at="2019-10-24T21:00:51Z" finished-at="2019-10-24T21:00:53Z">
      <class name="getRequest.GetDataId">
        <test-method status="PASS" signature="getEndPointId()[pri:0, instance:getRequest.GetDataId@59f99ea]" name="getEndPointId" is-config="true" duration-ms="1993" started-at="2019-10-24T21:00:51Z" finished-at="2019-10-24T21:00:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEndPointId -->
        <test-method status="PASS" signature="testResponseCode()[pri:0, instance:getRequest.GetDataId@59f99ea]" name="testResponseCode" duration-ms="9" started-at="2019-10-24T21:00:53Z" finished-at="2019-10-24T21:00:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseCode -->
        <test-method status="PASS" signature="testResponseDataId()[pri:0, instance:getRequest.GetDataId@59f99ea]" name="testResponseDataId" duration-ms="567" started-at="2019-10-24T21:00:53Z" finished-at="2019-10-24T21:00:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseDataId -->
        <test-method status="PASS" signature="testResponseLine()[pri:0, instance:getRequest.GetDataId@59f99ea]" name="testResponseLine" duration-ms="1" started-at="2019-10-24T21:00:53Z" finished-at="2019-10-24T21:00:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseLine -->
        <test-method status="FAIL" signature="validateDataType()[pri:0, instance:getRequest.GetDataId@59f99ea]" name="validateDataType" duration-ms="20" started-at="2019-10-24T21:00:53Z" finished-at="2019-10-24T21:00:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [String] but found [float]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [String] but found [float]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at getRequest.GetDataId.validateDataType(GetDataId.java:143)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDataType -->
        <test-method status="PASS" signature="validateHeaders()[pri:0, instance:getRequest.GetDataId@59f99ea]" name="validateHeaders" duration-ms="2" started-at="2019-10-24T21:00:53Z" finished-at="2019-10-24T21:00:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHeaders -->
        <test-method status="FAIL" signature="validateResponseBody()[pri:0, instance:getRequest.GetDataId@59f99ea]" name="validateResponseBody" duration-ms="1" started-at="2019-10-24T21:00:53Z" finished-at="2019-10-24T21:00:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [product-code] but found [id]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [product-code] but found [id]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at getRequest.GetDataId.validateResponseBody(GetDataId.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateResponseBody -->
      </class> <!-- getRequest.GetDataId -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
